apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: bookcamp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: manikanta8080/myapp:1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: database_url